### ISSUE TITLE
lcl-gateway.py ethernet timeout issue

### ISSUE THREAD

**Issue by aktarsius** [lechacal/lcl-gateway.py#6]
I have had the lcl-gateway.py program crash a few times, and I’ve captured the following log. Could you give me any clues as to the problem? It looks like a network issue, but its connected via Ethernet, and the other devices on the same switch were all fine, including my EmonTX unit which continued to log up to emoncms.org. Not sure if its a case of the emoncms.org server responding slowly, or a general slow connection. My ethernet connection is via Fibre to the house, typically very fast.
 
Log capture:
INFO: Reading data from /dev/ttyAMA0
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 382, in _make_request
self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 1012, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 411, in connect
    self.sock = ssl_wrap_socket(
  File "/usr/lib/python3/dist-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/usr/lib/python3/dist-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.9/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.9/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/lib/python3.9/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
socket.timeout: _ssl.c:1106: The handshake operation timed out
 
During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 532, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/lib/python3/dist-packages/six.py", line 719, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 385, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=conn.timeout)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 336, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='emoncms.org', port=443): Read timed out. (read timeout=5)
 
During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):
  File "/usr/local/bin/lcl-gateway.py", line 149, in <module>
    post_to_url(session, url, data=payload)
  File "/usr/local/bin/lcl-gateway.py", line 22, in post_to_url
    r = session.post(*args, **kwargs, timeout=HTTP_TIMEOUT)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 590, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='emoncms.org', port=443): Read timed out. (read timeout=5)
 
Thanks in advance

Andrew K

**Comment by lechacal** [comment]
For the time being you can modify the line below.
[HTTP_TIMEOUT=5](https://github.com/lechacal/lcl-gateway.py/blob/ca12024a5a2bf26e7a1512f0d21513728cdd7b72/lcl-gateway.py#L20C1-L20C15)

Let us know if increasing the timeout to 30 seconds improves anything.

We might have to get the timeout configurable from the config file at some point. 

Also we would probably need to add some management to the  requests.exceptions.ReadTimeout. From line 44 something like
except requests.exceptions.ReadTimeout as e:
    logging.warning("ConnectionTimeout: %s", e)

Although this would discard the data being sent but doing otherwise would be rather complex. At least the program would not stop running.

Keep us informed Andrew if you come to try this before we have a chance.

**Comment by aktarsius** [comment]
Increasing the Timeout to 30 seconds has made a huge improvement already: no crashes in over 72 hours, compared with every 4 or 5 hours or less, using the default 5 second timeout.

When I get a chance, I will have a look at adding exception handling, retries and local caching to see how it goes.

Cheers

Andrew

**Comment by aktarsius** [comment]
Update to my last post: by coincidence, a power outage meant that I lost Internet connectivity for a couple of hours overnight. The software crashed (as was possibly expected for such a long period of disconnection), so I will make some effort in adding retries for an extended period, and cache data locally.
